version: '3'

tasks:
  dev:
    cmds:
      - task: watch:tailwind & air main.go
  build:dependencies:
    desc: "run dependency builds"
    deps:
      - build:templates
      - build:buf
  build:templates:
    desc: "build templ files"
    cmds:
      - templ generate
  build:tailwind:
    desc: "build tailwind css"
    cmds:
      - npx tailwindcss -i ./static/input.css -o ./static/output.css 
  watch:tailwind:
    desc: "watch tailwind css"
    cmds:
      - npx tailwindcss -i ./static/input.css -o ./static/output.css --watch 
  build:buf:
    desc: "Generate event go code from proto files"
    dir: "events"
    cmds:
      - buf generate
